In [1]:
import numpy as np

In [4]:
# level 1.1

a = np.array([15, 32, 0])
b = np.array([-32, -18, 25])

np.dot(a, b)

-1056

In [6]:
# level 1.2
# 1
A = np.array([[5, 10, 1],
              [0, 1, 0],
              [9, 3, 6]])

# a)
B1 = np.array([
    [1, 7, 3],
    [0, 2, 0],
    [9, 4, 2]
])

print(f'a: {A @ B1}')

# b)
B2 = np.array([
    [5, 1, 8],
    [2, 6, 3],
    [1, 3, 0]
])

print(f'b: {A @ B2}')

a: [[14 59 17]
 [ 0  2  0]
 [63 93 39]]
b: [[46 68 70]
 [ 2  6  3]
 [57 45 81]]


In [8]:
# 2
A = np.array([
    [5, 1, 8],
    [2, 6, 3],
    [1, 3, 0]
])

print(A.T)

[[5 2 1]
 [1 6 3]
 [8 3 0]]


In [9]:
# 3

print(np.linalg.inv(A))

[[ 0.21428571 -0.57142857  1.07142857]
 [-0.07142857  0.19047619 -0.02380952]
 [-0.          0.33333333 -0.66666667]]


In [16]:
# level 2
robo_cats = np.array([[100, 200, 1000],
                     [350, 150, 55],
                     [30, 30, 30]])

expenditures = np.array([2600, 1660, 210])

print(np.linalg.solve(robo_cats, expenditures), 'лапок, мордочек и хвостиков соответственно.')

[4. 1. 2.] лапок, мордочек и хвостиков соответственно
